export const Genres = [
    "Pop",
    "Rock",
    "Hip-Hop",
    "Rap",
    "R&B",
    "Soul",
    "Jazz",
    "Blues",
    "Country",
    "Folk",
    "Classical",
    "Electronic",
    "EDM",
    "Metal",
    "Reggae",
    "Gospel",
    "Spiritual",
    "Latin",
    "Indie",
    "Alternative",
    "K-Pop",
    "J-Pop",
    "Bollywood"
]
export const Moods =[   "Romantic",
    "Sad",
    "Happy",
    "Chill",
    "Energetic",
    "Party",
    "Workout",
    "Focus",
    "Study",
    "Relaxing",
    "Inspirational",
    "Aggressive",
    "Calm",
    "Meditative",
    "Nostalgic"];

export  const situationalGenres=[
    "Road Trip",
    "Rainy Day",
    "Morning",
    "Night",
    "Festival",
    "Love",
    "Breakup",
    "Dance",
    "Travel",
    "Wedding",
    "Sleep",
]
  